// Code generated by protoc-gen-go.
// source: imagelist/imagelist.proto
// DO NOT EDIT!

/*
Package imagelist is a generated protocol buffer package.

It is generated from these files:
	imagelist/imagelist.proto

It has these top-level messages:
	Empty
	ImageListReply
*/
package imagelist

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// The response message containing the greetings
type ImageListReply struct {
	ImageName []string `protobuf:"bytes,1,rep,name=imageName" json:"imageName,omitempty"`
}

func (m *ImageListReply) Reset()                    { *m = ImageListReply{} }
func (m *ImageListReply) String() string            { return proto.CompactTextString(m) }
func (*ImageListReply) ProtoMessage()               {}
func (*ImageListReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*Empty)(nil), "imagelist.Empty")
	proto.RegisterType((*ImageListReply)(nil), "imagelist.ImageListReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for ImageLister service

type ImageListerClient interface {
	// Sends a greeting
	ListImages(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ImageListReply, error)
}

type imageListerClient struct {
	cc *grpc.ClientConn
}

func NewImageListerClient(cc *grpc.ClientConn) ImageListerClient {
	return &imageListerClient{cc}
}

func (c *imageListerClient) ListImages(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ImageListReply, error) {
	out := new(ImageListReply)
	err := grpc.Invoke(ctx, "/imagelist.ImageLister/ListImages", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ImageLister service

type ImageListerServer interface {
	// Sends a greeting
	ListImages(context.Context, *Empty) (*ImageListReply, error)
}

func RegisterImageListerServer(s *grpc.Server, srv ImageListerServer) {
	s.RegisterService(&_ImageLister_serviceDesc, srv)
}

func _ImageLister_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageListerServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imagelist.ImageLister/ListImages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageListerServer).ListImages(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _ImageLister_serviceDesc = grpc.ServiceDesc{
	ServiceName: "imagelist.ImageLister",
	HandlerType: (*ImageListerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListImages",
			Handler:    _ImageLister_ListImages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("imagelist/imagelist.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 127 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0xcc, 0xcc, 0x4d, 0x4c,
	0x4f, 0xcd, 0xc9, 0x2c, 0x2e, 0xd1, 0x87, 0xb3, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x38,
	0xe1, 0x02, 0x4a, 0xec, 0x5c, 0xac, 0xae, 0xb9, 0x05, 0x25, 0x95, 0x4a, 0x7a, 0x5c, 0x7c, 0x9e,
	0x20, 0x51, 0x1f, 0xa0, 0x68, 0x50, 0x6a, 0x41, 0x4e, 0xa5, 0x90, 0x0c, 0x17, 0x44, 0x9d, 0x5f,
	0x62, 0x6e, 0xaa, 0x04, 0xa3, 0x02, 0xb3, 0x06, 0x67, 0x10, 0x42, 0xc0, 0xc8, 0x8b, 0x8b, 0x1b,
	0xae, 0x3e, 0xb5, 0x48, 0xc8, 0x9a, 0x8b, 0x0b, 0xc4, 0x02, 0x0b, 0x15, 0x0b, 0x09, 0xe8, 0x21,
	0xac, 0x04, 0x1b, 0x2f, 0x25, 0x89, 0x24, 0x82, 0x6a, 0x8f, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0x59,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x32, 0x9b, 0x3a, 0xb3, 0x00, 0x00, 0x00,
}
